### ISSUE TITLE
updated

### ISSUE THREAD

**Issue by lpengxue** [daringpig/DSA_DRQN_updated#1]
您好，请问您关于该代码是否有具体的report总结麽?

**Comment by daringpig** [comment]
没有，这个库好久了，缺乏维护。你是拿这个方向做毕业论文嘛？

**Comment by lpengxue** [comment]
非常感谢您的回复。我目前要做的是多用户同时竞争多个子信道的优化问题，我的优化目标是最小化多个智能体的AoI。我是想参考DSA_DRQN的代码，看到了您这里有注释的代码而且是进行了改进的，我复现了该代码后https://github.com/daringpig/RL-DSA，有些问题我不是很明白，可能是因为我对强化学习还不够理解，如果可以的话，您能帮我解答下麽？问题如下：iteration 是包含多个episodes, episodes包含多个time slots，https://github.com/daringpig/DSA_DRQN_updated我看到了episodes，但是源代码https://github.com/daringpig/RL-DSA里的结果图都是以time slot来衡量的，在源代码中我也没有看到episodes，Deep-Reinforcement-Learning-for-Dynamic-Spectrum-Access论文中的图2横轴也是time slot， 我在复现论文中图2的时候平均信道利用率随着时隙的波动比较大，论文中是逐渐趋于0.8，这点我比较迷惑，您是否可以帮我解答呢？非常感谢。 此外您对我要做的优化问题有什么建议麽？这个模型是否合适？



在 2024-01-08 19:13:41，"learner" ***@***.***> 写道：

没有，这个库好久了，缺乏维护。你是拿这个方向做毕业论文嘛？

**Comment by lpengxue** [comment]
> 没有，这个库好久了，缺乏维护。你是拿这个方向做毕业论文嘛？

您好，非常感谢您的回复。我现在要做的是多用户利用OFDMA技术同时接入多个子信道的问题，优化的目标是最小化多个智能体的AoI，想在这个代码的基础上做。我是想基于集中式训练，分布式执行来解决我的多智能体优化问题。这个代码的训练部分是集中式训练，eval评估部分算是分布式执行部分麽？我能私下和您进行一次更详细的讨论麽？当时这个代码有对应的论文发表么，我没有搜到。非常感谢您！
